create table student (student_id integer not null, student_name varchar(255), primary key (student_id)) engine=InnoDB;
create table student_seq (next_val bigint) engine=InnoDB;
insert into student_seq values ( 1 );
create table student (student_id integer not null, student_name varchar(255), primary key (student_id)) engine=InnoDB;
create table student_seq (next_val bigint) engine=InnoDB;
insert into student_seq values ( 1 );
create table student (student_id integer not null, student_name varchar(255), primary key (student_id)) engine=InnoDB;
create table student_seq (next_val bigint) engine=InnoDB;
insert into student_seq values ( 1 );
create table student (student_id integer not null, student_name varchar(255), primary key (student_id)) engine=InnoDB;
create table student_seq (next_val bigint) engine=InnoDB;
insert into student_seq values ( 1 );
create table student (student_id integer not null, student_name varchar(255), primary key (student_id)) engine=InnoDB;
create table student_seq (next_val bigint) engine=InnoDB;
insert into student_seq values ( 1 );
create sequence student_seq start with 1 increment by 50;
create table student (student_id integer not null, student_name varchar(255), primary key (student_id));
create sequence student_seq start with 1 increment by 50;
create table student (student_id integer not null, student_name varchar(255), primary key (student_id));
create table student (student_id integer not null, student_name varchar(255), primary key (student_id)) engine=InnoDB;
create table student_seq (next_val bigint) engine=InnoDB;
insert into student_seq values ( 1 );
create table student (student_id integer not null, student_name varchar(255), primary key (student_id)) engine=InnoDB;
create table student_seq (next_val bigint) engine=InnoDB;
insert into student_seq values ( 1 );
create table student (student_id integer not null, student_name varchar(255), primary key (student_id)) engine=InnoDB;
create table student_seq (next_val bigint) engine=InnoDB;
insert into student_seq values ( 1 );
create table student (student_id integer not null, student_name varchar(255), primary key (student_id)) engine=InnoDB;
create table student_seq (next_val bigint) engine=InnoDB;
insert into student_seq values ( 1 );
create table student (student_id integer not null, student_name varchar(255), primary key (student_id)) engine=InnoDB;
create table student_seq (next_val bigint) engine=InnoDB;
insert into student_seq values ( 1 );
create table student (student_id integer not null, student_name varchar(255), primary key (student_id)) engine=InnoDB;
create table student_seq (next_val bigint) engine=InnoDB;
insert into student_seq values ( 1 );
create table student (student_id integer not null, student_name varchar(255), primary key (student_id)) engine=InnoDB;
create table student_seq (next_val bigint) engine=InnoDB;
insert into student_seq values ( 1 );
create table student (student_id integer not null, student_name varchar(255), primary key (student_id)) engine=InnoDB;
create table student_seq (next_val bigint) engine=InnoDB;
insert into student_seq values ( 1 );
create table student (student_id integer not null, student_name varchar(255), primary key (student_id)) engine=InnoDB;
create table student_seq (next_val bigint) engine=InnoDB;
insert into student_seq values ( 1 );
create sequence student_seq start with 1 increment by 50;
create table student (student_id integer not null, student_name varchar(255), primary key (student_id));
create table student (student_id integer not null, student_name varchar(255), primary key (student_id)) engine=InnoDB;
create table student_seq (next_val bigint) engine=InnoDB;
insert into student_seq values ( 1 );
create table student (student_id integer not null, student_name varchar(255), primary key (student_id)) engine=InnoDB;
create table student_seq (next_val bigint) engine=InnoDB;
insert into student_seq values ( 1 );
create table student (student_id integer not null, student_name varchar(255), primary key (student_id)) engine=InnoDB;
create table student_seq (next_val bigint) engine=InnoDB;
insert into student_seq values ( 1 );
create table student (student_id integer not null, student_name varchar(255), primary key (student_id)) engine=InnoDB;
create table student_seq (next_val bigint) engine=InnoDB;
insert into student_seq values ( 1 );
create table student (student_id integer not null, student_name varchar(255), primary key (student_id)) engine=InnoDB;
create table student_seq (next_val bigint) engine=InnoDB;
insert into student_seq values ( 1 );
create table student (student_id integer not null, student_name varchar(255), primary key (student_id)) engine=InnoDB;
create table student_seq (next_val bigint) engine=InnoDB;
insert into student_seq values ( 1 );
create table student (student_id integer not null, student_name varchar(255), primary key (student_id)) engine=InnoDB;
create table student_seq (next_val bigint) engine=InnoDB;
insert into student_seq values ( 1 );
